tutorial-cjtests-snowflake-db:
    target: dev
    outputs:
        dev:
            type: snowflake
            account: {redacted}

            #User / Password auth
            user: {redacted}
            password: {redacted}

            role: TRANSFORM_ROLE
            database: ANALYTICS
            warehouse: "TRANSFORM_WH"
            schema: DBT
            threads: 1
            client_session_keep_alive: False

