
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: snowflake_customer_purchases
    description: "A query using snowflake tables"
    columns:
      - name: c_custkey
        description: "customer_id"
        tests:
          - unique

  - name: cumulative_orders_by_date
    description: "cumulative orders query"
    columns:
      - name: o_orderdate
        description: "order date"

  - name: incremental_time

sources:
  - name: sample
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: orders

      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null


